# Generated by Django 4.0.2 on 2022-03-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restnotifications',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restnotifications',
            name='notif_type',
            field=models.CharField(choices=[('l', 'like'), ('f', 'follow'), ('c', 'comment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='notif_type',
            field=models.CharField(choices=[('m', 'menu change'), ('b', 'new blog posted')], max_length=1),
        ),
    ]
