# Generated by Django 4.0.2 on 2022-03-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_comment_mid_menuitem_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='mid',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='../media/koala.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
