# Generated by Django 4.0.2 on 2022-03-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_menu_rid_remove_menuitem_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='../media/koala.jpg', upload_to=''),
        ),
    ]
