# Generated by Django 4.0.3 on 2022-04-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('m', 'menu change'), ('n', 'new item'), ('b', 'blog added')], max_length=1)),
                ('description', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(blank=True, default='../media/koala.jpg', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('l', 'like'), ('f', 'follow'), ('c', 'comment')], max_length=1)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
