# Generated by Django 4.0.3 on 2022-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
