# Generated by Django 4.0.2 on 2022-03-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_groups_alter_myuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
