# Generated by Django 4.0.3 on 2022-04-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownernotifications',
            name='logo',
            field=models.ImageField(blank=True, default='../media/koala.jpg', upload_to=''),
        ),
    ]
